
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    service-feign: /api-b/**
    api-c:
      path: /api-a/**
      serviceId: service-ribbon-hystrix
  ignored-services:
    - client-hi
    - service-ribbon-hystrix
#  prefix: /api-b
